# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'easydbi-firebird'
description: 'Firebird database adapter for easydbi'
version: '0.1.0'
repository:
  type: 'git'
  url: 'git://github.com/yinso/easydbi-firebird.git'
main: './lib/main'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
  easydbi: =0.1.0
  coffee-script: =1.8.0
  underscore: =1.7.0
  node-uuid: =1.4.1
  async: =0.9.0
  firebird: '>=0.0.10'
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '=0.3.0'
  
