// Generated by CoffeeScript 1.4.0
(function() {
  var Promise, async, loglet;

  async = require('async');

  loglet = require('loglet');

  Promise = (function() {

    Promise.make = function() {
      return new Promise();
    };

    function Promise() {
      this.calls = [];
      this.error = console.error;
      this;

    }

    Promise.prototype.then = function(proc) {
      if (proc.length === 1) {
        this.calls.push(function(cb) {
          try {
            return proc(cb);
          } catch (e) {
            return cb(e);
          }
        });
      } else {
        this.calls.push(function(res, cb) {
          try {
            return proc(res, cb);
          } catch (e) {
            return cb(e);
          }
        });
      }
      return this;
    };

    Promise.prototype["catch"] = function(error) {
      this.error = error;
      return this;
    };

    Promise.prototype.done = function(lastCB) {
      var helper, interim, self;
      if (lastCB == null) {
        lastCB = function() {};
      }
      self = this;
      interim = null;
      helper = function(call, next) {
        var cb;
        cb = function(err, res) {
          loglet.debug('cb======', err, interim);
          if (err) {
            return next(err);
          } else {
            interim = res;
            return next(null);
          }
        };
        if (call.length > 1) {
          return call(interim, cb);
        } else {
          loglet.debug('helper-non-interim', call);
          return call(cb);
        }
      };
      async.eachSeries(this.calls, helper, function(err) {
        try {
          if (err) {
            return self.error(err);
          } else {
            return lastCB();
          }
        } catch (e) {
          return lastCB(e);
        }
      });
      return this;
    };

    return Promise;

  })();

  module.exports = Promise;

}).call(this);
